repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        exclude: (poetry.lock|pyproject.toml)
        language: system
        types: [ python ]

      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
        args: ["--profile", "black"]

      - id: flake8
        name: flake8
        entry: flake8
        exclude: (poetry.lock|pyproject.toml)
        language: system
        types: [ python ]
        args: ['--max-line-length=89']
