repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        exclude: (poetry.lock|pyproject.toml)
        language: system
        types: [ python ]

      - id: reorder-python-imports
        name: reorder-python-imports
        entry: reorder-python-imports
        language: system
        types: [ python ]
        args: [ --py37-plus ]

      - id: flake8
        name: flake8
        entry: flake8
        exclude: (poetry.lock|pyproject.toml)
        language: system
        types: [ python ]
        args: ['--max-line-length=89']
