version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  flask:
    build:
      context: .
      target: flask
    ports:
      - "5001:5001"
    depends_on:
      - mongo


  rabbit:
    build:
       context: .
       target: rabbitmq
    networks:
      - rabbit-network


networks:
  rabbit-network:
    external: true