version: "3"

services:
  rabbit:
    container_name: 'rabbit_mq'
    image: "rabbitmq:3-management"
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "15672:15672"
      - "5672:5672"

  websockets:
    build:
      context: .
    container_name: 'websockets_chat'
    ports:
      - "8080:8080"
