version: "3.7"

services:
  mongodb-test:
    image: mongo
    container_name: "mongo_db_test"
    ports:
      - "27018:27017"
    volumes:
      - mongodb-test-data:/data/db

  mongo_db:
    image: mongo
    container_name: "mongo_db"
    ports:
      - "27017:27017"


  redis_cash:
    image: 'bitnami/redis:latest'
    container_name: "redis_cash"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf


volumes:
  redis-data:
  redis-conf:
  mongodb-test-data:
