[tool.poetry]
name = "websockets-chat"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "websockets_chat"}]

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.22.0"
python-socketio = "^5.8.0"
aiohttp = "^3.8.4"
wsproto = "^1.2.0"
black = "^23.3.0"
flake8 = "^6.0.0"
mypy = "^1.3.0"
isort = "^5.12.0"
python-dotenv = "^1.0.0"
pre-commit = "^3.3.2"
aio-pika = "^9.0.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
