# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weather_commands.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16weather_commands.proto"\x1e\n\x0eWeatherRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t""\n\x0fWeatherResponse\x12\x0f\n\x07weather\x18\x01 \x01(\t2:\n\x07Weather\x12/\n\nGetWeather\x12\x0f.WeatherRequest\x1a\x10.WeatherResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "weather_commands_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_WEATHERREQUEST"]._serialized_start = 26
    _globals["_WEATHERREQUEST"]._serialized_end = 56
    _globals["_WEATHERRESPONSE"]._serialized_start = 58
    _globals["_WEATHERRESPONSE"]._serialized_end = 92
    _globals["_WEATHER"]._serialized_start = 94
    _globals["_WEATHER"]._serialized_end = 152
# @@protoc_insertion_point(module_scope)
