# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import weather_commands_pb2 as weather__commands__pb2


class WeatherStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWeather = channel.unary_unary(
            "/Weather/GetWeather",
            request_serializer=weather__commands__pb2.WeatherRequest.SerializeToString,
            response_deserializer=weather__commands__pb2.WeatherResponse.FromString,
        )


class WeatherServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetWeather(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_WeatherServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetWeather": grpc.unary_unary_rpc_method_handler(
            servicer.GetWeather,
            request_deserializer=weather__commands__pb2.WeatherRequest.FromString,
            response_serializer=weather__commands__pb2.WeatherResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "Weather", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Weather(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetWeather(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/Weather/GetWeather",
            weather__commands__pb2.WeatherRequest.SerializeToString,
            weather__commands__pb2.WeatherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
